#cloud-config
disable_root: false
hostname: liyi-linux
ssh_pwauth: false
users:
  - name: liyi
    groups: sudo
    passwd: $6$xANsKi6P9WIabL1Z$BbTK6yrVJbNSc0OTbRtIjpvPdJHGFv.cm2wPVOPJuS2ysdwKVKEAtB6GRjiOn/sf0vjizhYEQ8A8qLUSiFwDI.
    lock_passwd: false
    shell: /bin/zsh
    sudo: ALL=(ALL) NOPASSWD:ALL
    ssh_authorized_keys:
      - ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQDCMXSakoFcF1EjZ4H0W13LlF3ZXFE7a6+u3vt5+8bW9u54n4Q4R6GJaroKC7gCCRcwJWhIpar85CBXmmNMYGN/blf6pVo6QaXawaDhi5gIJFazdScPnzKG5QndIOEOvGJfLCRqMRby4e17EJPBE4URIGTmuo9LP744LD23dA6JWwOfV/dMGXS/g2Lwiw74qzw/nM6A1QtKf/QCT2Wds27j+2471+Jiaf+xBctXrjh0NoY1ldLl6BrhsF81HRosOfQhsCzqq0rrt+ER874z9N7Yyk0ZVf1i5Hp5NdiCuSwTlEd2COz3oVIh8RwCeXlcr22qvDEgbgF5Xkk/wRJ8CRPd
package_update: true
packages:
  - git
  - curl
  - tmux
  - zsh
  - vim
  - jq
  - tmate
 # - podman
 # - xorg
 # - termshark
 # - openbox

runcmd:
  - echo "installing the kubectx"
  - sudo snap install kubectx --classic

  - echo "Installing Kubectl(copy and paste from https://kubernetes.io/docs/tasks/tools/install-kubectl-linux/)"
  - sudo snap install kubectl --classic

  - echo "installing terraform (copy and paste from https://developer.hashicorp.com/terraform/tutorials/aws-get-started/install-cli)" 
  - sudo snap install terraform --classic

  - echo "installaing the helm"
  - sudo snap install helm --classic

  - echo "installing the cilium CLI"
  - CILIUM_CLI_VERSION=$(curl -s https://raw.githubusercontent.com/cilium/cilium-cli/main/stable.txt)
  - CLI_ARCH=amd64
  - if [ "$(uname -m)" = "aarch64" ]; then CLI_ARCH=arm64; fi
  - curl -L --fail --remote-name-all https://github.com/cilium/cilium-cli/releases/download/${CILIUM_CLI_VERSION}/cilium-linux-${CLI_ARCH}.tar.gz{,.sha256sum}
  - sha256sum --check cilium-linux-${CLI_ARCH}.tar.gz.sha256sum
  - sudo tar xzvfC cilium-linux-${CLI_ARCH}.tar.gz /usr/local/bin
  - rm cilium-linux-${CLI_ARCH}.tar.gz{,.sha256sum}

  - echo "installing the kubecm"
  - curl -Lo kubecm.tar.gz https://github.com/sunny0826/kubecm/releases/download/v0.25.0/kubecm_v0.25.0_Linux_arm64.tar.gz
  - tar -zxvf kubecm.tar.gz kubecm
  - sudo mv kubecm /usr/local/bin/
  
  - echo "download cloudinit from github"
  - git clone https://github.com/liyihuang/liyi-cloudinit.git /home/liyi/liyi-cloudinit
  - chown -R liyi:liyi /home/liyi/liyi-cloudinit
  - echo "run personal setup script"
  - runuser -l liyi -c '/home/liyi/liyi-cloudinit/setup.sh'
